package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
)

const (
	dsn       = "host=localhost port=5432 user=user password=password dbname=bioly sslmode=disable"
	N         = 100_000
	batchSize = 1000
)

func main() {
	db, err := sqlx.Connect("postgres", dsn)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	log.Printf("start seeding %d users\n", N)

	for offset := 0; offset < N; offset += batchSize {
		limit := batchSize
		if offset+limit > N {
			limit = N - offset
		}

		if err := insertBatch(db, offset, limit); err != nil {
			log.Fatalf("batch insert failed at offset %d: %v", offset, err)
		}

		log.Printf("inserted %d users", offset+limit)
	}

	log.Println("done")
}

func insertBatch(db *sqlx.DB, offset, limit int) error {
	tx, err := db.Beginx()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	userIDs, err := insertUsersBatch(tx, offset, limit)
	if err != nil {
		return err
	}

	if err := insertProfilesBatch(tx, userIDs); err != nil {
		return err
	}

	return tx.Commit()
}

func insertUsersBatch(tx *sqlx.Tx, offset, limit int) ([]int64, error) {
	query := `INSERT INTO auth.users (username, password_hash) VALUES `
	args := make([]any, 0, limit*2)
	argPos := 1

	const passwordHash = "$argon2id$v=19$m=65536,t=1,p=10$test$testhash"

	for i := 0; i < limit; i++ {
		if i > 0 {
			query += ","
		}
		query += fmt.Sprintf(" ($%d, $%d)", argPos, argPos+1)

		args = append(
			args,
			fmt.Sprintf("user_%d", offset+i),
			passwordHash,
		)
		argPos += 2
	}

	query += " RETURNING id"

	rows, err := tx.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	ids := make([]int64, 0, limit)
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}

	return ids, nil
}

func insertProfilesBatch(tx *sqlx.Tx, userIDs []int64) error {
	query := `INSERT INTO profiles.user_page (user_id, page) VALUES `
	args := make([]any, 0, len(userIDs)*2)
	argPos := 1

	for i, userID := range userIDs {
		if i > 0 {
			query += ","
		}

		page := map[string]any{
			"title": "Bioly user page",
			"bio":   "Autogenerated profile",
			"links": []map[string]string{
				{
					"type": "telegram",
					"url":  fmt.Sprintf("https://t.me/user%d", userID),
				},
			},
			"theme": "light",
		}

		pageJSON, err := json.Marshal(page)
		if err != nil {
			return err
		}

		query += fmt.Sprintf(" ($%d, $%d)", argPos, argPos+1)
		args = append(args, userID, pageJSON)
		argPos += 2
	}

	_, err := tx.Exec(query, args...)
	return err
}
